#! /bin/bash

#Listing files in the current directory

for obj in ./*; do
    if [ -d "$obj" ]; then
        echo "$obj is a folder"
    elif [ -f "$obj" ]; then
        echo "$obj is a file"
    fi
done
