#! /bin/bash

read -p "
Let's get started! :)

Choose the cluster in which you'd like to work in. Options are:

1. Production cluster
2. Development cluster

Type your option here ( choose a number ): " env_option

if [ $env_option = 1 ]; then
    echo "

You are now in a ==== PRODUCTION ==== environment. Be VERY careful from now on :)

"
    export KOPS_STATE_STORE=s3://prod-k8s-navenio-com
    kops export kubecfg wta-prod-eu-west-1.k8s.local

elif [ $env_option = 2 ]; then

    #kops export kubecfg devs.k8s.local
    export K8_CLUSTER_NAME=devs.k8s.local
    export KOPS_STATE_STORE=s3://kubernetes-navenio-com
    kops export kubecfg devs.k8s.local
    echo "
    Context set to devs.k8s.local
    "
fi
echo ""
kubectl get ns
echo ""
read -p "Choose a namespace from the list above (please type it in) : " namespace
echo ""
kubectl config set-context --current --namespace $namespace
echo ""
kubectl get deployments
echo ""
read -p "Choose the deployment that you want to restart (please type it in): " deployment_name
kubectl -n $namespace rollout restart deployment $deployment_name
echo "Rollout restart in progress. Please use -- kubectl get pods -- as a command for querying the status of the pods after the restart"
